### ISSUE TITLE
add button to upload isotherm JSON

### ISSUE THREAD

**Issue by ltalirz** [NIST-ISODB/isotherm-digitizer-panel#12]

**Comment by dwsideriusNIST** [comment]
An initial version of this feature is in https://github.com/dwsideriusNIST/isotherm-digitizer-panel/tree/feature-read_json

There are some issues with the form layout and the code to read from JSON is clunky.

**Comment by ltalirz** [comment]
opened https://github.com/ltalirz/isotherm-digitizer-panel/pull/47

**Comment by ltalirz** [comment]
fixed in https://github.com/ltalirz/isotherm-digitizer-panel/pull/52
