### ISSUE TITLE
isotherm_type: add "Unknown"?

### ISSUE THREAD

**Issue by ltalirz** [NIST-ISODB/isotherm-digitizer-panel#14]
@danieleongari wonders whether it is always possible to be sure

@dwsideriusNIST

**Comment by dwsideriusNIST** [comment]
Very good point for consideration: I do not think that it is always possible to to be sure of the isotherm type, especially for non-experts, but even for experts.

For the PHP digitizer, this was an optional attribute for an isotherm. I instructed my students to choose the isotherm type **only** if the source article clearly stated the type.

**Comment by ltalirz** [comment]
fixed in 4ffa57b369804318c8a2cbcdd493ee5a34afeffb
