### ISSUE TITLE
create bibliography for submission to isodb

### ISSUE THREAD

**Issue by ltalirz** [NIST-ISODB/isotherm-digitizer-panel#20]
See https://github.com/dwsideriusNIST/isodb-library/blob/2f2883df7bc8de13758334d014e0404c1d4d9a9e/utilities.py#L407-L457

@dwsideriusNIST will ping me when this code is completed

**Comment by dwsideriusNIST** [comment]
The script to do this is now part of https://github.com/dwsideriusNIST/isodb-library, in the bibliography.py module.

This raises a new concern: some scripts may now be needed by both the digitizer and isodb-library repos. It may be valuable to move all of the library manipulation scripts (basically, *.py in the root dir of dwsideriusNIST/isodb-library) to a separate repo, then add it as a submodule to both isodb-library and isotherm-digitizer-panel

**Comment by ltalirz** [comment]
Sounds good, we can can have an `isodb-tools` repo.

I would personally suggest to avoid git submodules and rather install it via pip (one can do so directly from github e.g. `pip install git+https://github.com/ltalirz/isotherm-digitizer-panel.git`).
In my experience git submodules are a bit tricky to deal with properly and can cause confusion.

**Comment by dwsideriusNIST** [comment]
Definitely true, submodules are a bit tricky, especially if > 1. Updates are always a bit "cross your fingers and check afterward." `isodb-tools` will be up today or tomorrow.

**Comment by dwsideriusNIST** [comment]
Tools are now at: https://github.com/dwsideriusNIST/isodb-tools

Package may (probably does) need modifications to be useful via pip

**Comment by dwsideriusNIST** [comment]
in the planned workflow, the `{isotherms} -> bibliography` steps are 1) after isotherm post-processing and 2) my job, so I do not think it should be part of the digitizer app. Recommend this issue be closed.

**Comment by ltalirz** [comment]
> Recommend this issue be closed.

Alright!
