### ISSUE TITLE
Case-sensitive during autocomplete search

### ISSUE THREAD

**Issue by dwsideriusNIST** [NIST-ISODB/isotherm-digitizer-panel#29]
Auto-fill only works correctly when the input text case matches the entry in the list.

e.g., "hkust-1" fails, but "HK" works

**Comment by dwsideriusNIST** [comment]
~~It looks like this was addressed a few months ago: https://github.com/bokeh/bokeh/issues/9922. According to release notes, this feature was added in bokeh 2.1.0. At present, however, the case-insensitive autocomplete is not working on my installation. (Anaconda is at bokeh 2.1.1.) May be a syntax issue to track down.~~

I did not understand which package was providing the autocomplete widget. It appears that panel.widgets does not support case insensitive autocomplete. I'm going to look upstream and see where/how it could be added.

**Comment by dwsideriusNIST** [comment]
This was straightforward to fix, one line addition to the holoviz/panel package: https://github.com/holoviz/panel/pull/1548

Problem is that we will not see proper support while the PR works its way into the official package releases. On the upside, the parameter addition to the digitizer does not break anything.

You can see the change to panel here: https://github.com/dwsideriusNIST/panel. For now, I've manually updated the package in my anaconda tree.

**Comment by dwsideriusNIST** [comment]
not fixed in panel 0.9.7, so I'm leaving this open

**Comment by ltalirz** [comment]
Ah great, thanks for directly contributing this upstream to panel!

I would say let's wait a little bit if a release drops (there is also the slightly more complex issue of adding new values, which I'll look into).

If it ends up taking too long, there is no problem in installing a fixed commit of the panel `develop` branch directly.

**Comment by ltalirz** [comment]
fixed by https://github.com/ltalirz/isotherm-digitizer-panel/pull/48
