### ISSUE TITLE
Concentration units API does not work

### ISSUE THREAD

**Issue by ltalirz** [NIST-ISODB/isotherm-digitizer-panel#3]
I found that the API for concentration units does not work: https://adsorption.nist.gov/isodb/api/concentration-type-lookup.json

**Comment by ltalirz** [comment]
Pinging @dwsideriusNIST about this

**Comment by dwsideriusNIST** [comment]
API call should be:
/isodb/api/concentration-units-lookup.json

**Comment by ltalirz** [comment]
Ah, thanks, that was rather obvious ;-)

I thought I tried this before, but if you enter an endpoint that the API does not understand, it redirects you to a different base url (https://adsorption.nist.gov/api/concentration-type-lookup.json ), i.e. I tried it but with the wrong base url.
