### ISSUE TITLE
parsing isotherm_data field

### ISSUE THREAD

**Issue by dwsideriusNIST** [NIST-ISODB/isotherm-digitizer-panel#32]
need to improve the data parsing of the isotherm_data input box.

CSV parsing is straightforward, but I've discovered that pasting from other applications leaves unpredictable delimiting of both the lines and data in the lines.

I have a solution that I'll push to a develop branch, but it's clunky

**Comment by ltalirz** [comment]
Yes, I suggest you create a feature branch for this and then make a PR.
I'll then have a look

**Comment by dwsideriusNIST** [comment]
See PR #35
