### ISSUE TITLE
plot button is adding traces to existing plot

### ISSUE THREAD

**Issue by dwsideriusNIST** [NIST-ISODB/isotherm-digitizer-panel#33]
If a user plots one isotherm, then goes back and clicks "plot data" again without reloading the panel, a new data trace is added to the plot figure. It should plot only the current isotherm.

This can be an issue because users will want to:

Fill in the form, paste in an isotherm and then generate the JSON
Go back to the form, modify the necessary parts, then generate JSON for the isotherm.

Reloading the panel app will clear out a lot of data that can be re-used to save effort.

**Comment by ltalirz** [comment]
Agreed, this is easy to fix

**Comment by dwsideriusNIST** [comment]
I'm assuming that this depends on a more recent version of panel, as the plot behaves oddly on my Mac (panel is mainline from conda-forge 0.9.7). The first instance of **Plot Data** is fine, but the second creates an overlay of the axes (maybe the data too, but I can't see anything):

<img width="650" alt="Screen Shot 2020-09-23 at 11 14 38 AM" src="https://user-images.githubusercontent.com/5341350/94032903-70ed3a80-fd8e-11ea-85aa-6f6ce30e9fee.png">

**Comment by ltalirz** [comment]
Thanks @dwsideriusNIST - I can reproduce this - this is a bug.
