### ISSUE TITLE
Minor issues during form-to-JSON step

### ISSUE THREAD

**Issue by dwsideriusNIST** [NIST-ISODB/isotherm-digitizer-panel#44]
some translation issues when generating JSON from the form:

1. "measurement_type" key should be "category". Also, the long category names should be converted to short (Simulation->sim)
2. If the value of one of the drop-downs is "Select" because the user didn't select it, should the app not include that key in the output or change "Select" to ""?
3. Same as #2 for null values ("associated_content" and "concentrationUnits")
4. the value of "pressureUnits" for relative pressure is "RELATIVE"

Post-processing scripts could handle some of them.

I'll work on these.

**Comment by ltalirz** [comment]
> If the value of one of the drop-downs is "Select" because the user didn't select it, should the app not include that key in the output or change "Select" to ""?

Indeed, this is something I overlooked.

Since this only applies to fields that are not required (otherwise, leaving 'Select' will prevent the form from being submitted), we may want to call the default option of those fields "Not specified" instead (such a field already exists e.g. for "Isotherm type").
We then still need to transform it to `null` in the JSON (`None` in python).

> Same as #2 for null values ("associated_content" and "concentrationUnits")

As far as I am aware, `null` is the [canonical way of representing a missing value in JSON](https://json-schema.org/understanding-json-schema/reference/null.html).
Is there a reason not to use it here?

> I'll work on these.

Great, thanks a lot for your help!

**Comment by dwsideriusNIST** [comment]
> Since this only applies to fields that are not required (otherwise, leaving 'Select' will prevent the form from being submitted), we may want to call the default option of those fields "Not specified" instead (such a field already exists e.g. for "Isotherm type").
> We then still need to transform it to `null` in the JSON (`None` in python).
> 
> > Same as #2 for null values ("associated_content" and "concentrationUnits")
> 
> As far as I am aware, `null` is the [canonical way of representing a missing value in JSON](https://json-schema.org/understanding-json-schema/reference/null.html).
> Is there a reason not to use it here?
> 
I have to check how the database admin system will deal with `null` and empty values in JSON uploads. Again, something we didn't envision while designing that system. (I would create an entirely different pipeline based on the work we've done in the last six months.) Similarly, the API outputs `null` key values as "".

If we change the 'not required' fields that are not filled to `null`, then the postprocessing script could handle cleanup.

Part of the problem is that there is not perfect symmetry between the JSON that is uploaded to the database and the JSON that is output by the API. For isotherms, I think some minor revision to the PHP engine can get us to perfect symmetry; same for adsorbents and adsorbates. Bibliography files are an entirely different situation: there's a whole lot of necessary information in the JSON upload file that the end user never sees in the API output. (In fact, if you look in the isodb-tools repo, the bibliography generating function has an option called `simulate_api` that deals with that lack of symmetry.)

(There are also some really ancient keys in the bibliography API for adsorbents and adsorbates that originated in the first version of the database schema, but were since superseded. We didn't want to outright delete a key. Perhaps I'll increment the API to version 3, drop those keys, and post a big _caveat emptor_ sign.)

**Comment by dwsideriusNIST** [comment]
On the positive side, these issues are cropping up because I'm using the panel for actual data operations. There will be several commits to isodb-library based on work done in the panel.

**Comment by ltalirz** [comment]
Yes, let me know about the `null` vs empty string issue.
In the long run, I believe following accepted standards tends to make your life easier as things like editors / validators can then automagically pick up on things.
At the same time I don't want to force updates of an existing format if it causes a lot of extra work, and there may be something to be said for keeping the same approach to values that are not specified in the "raw" JSON and in the postprocessed one. It's a balancing act.

I leave this up to you to wreck your brain about and come to a decision ;-)

> Perhaps I'll increment the API to version 3, drop those keys, and post a big caveat emptor sign

Sounds reasonable to me.

> On the positive side, these issues are cropping up because I'm using the panel for actual data operations. There will be several commits to isodb-library based on work done in the panel.

That's great!

I'm very much looking forward to my bokeh PR being merged (unfortunately such things take their time); and once we have it working in panel as well, we're almost good to go :-)

**Comment by dwsideriusNIST** [comment]
PR #46 covers these issues. As described in the PR text, there is a 'hacky' element to the corrections and I view them as temporary, though necessary, until API upgrades are finished.

**Comment by dwsideriusNIST** [comment]
the final commits to #46 should address remaining concerns in this issue. The 'hacky' element is gone with the understanding that those corrections are made in postprocessing.

**Comment by dwsideriusNIST** [comment]
#53 covers this issue
