### ISSUE TITLE
logarithmic pressure scale unhandled

### ISSUE THREAD

**Issue by ltalirz** [NIST-ISODB/isotherm-digitizer-panel#5]
Do I need to do anything with the checkbox for logarithmic pressures?
Should this not be handled on the digitizer side?

**Comment by dwsideriusNIST** [comment]
Yes, the post-processing script converts from logarithmic pressure to nominal, unit-ized pressure.

That conversion is non-trivial - it depends on 1) whether the argument of the log is a reduced pressure [in which case, the saturation pressure has to be specified] or 2) whether the argument of the log is a plain pressure (which is sloppy) [in which case, the units still have to be specified]

My SOP with the php-based digitizer was to create a "logscale" Boolean variable in output JSON, which the post-processing script used to decide the conversion procedure.

**Comment by ltalirz** [comment]
Clarification: Dan instructed his students to enter the exponent (since it is the linear scale).
Since our digitizer can handle this, we may not need this option (?)

**Comment by ltalirz** [comment]
@dwsideriusNIST : if you add a log-scale figure, it will preview in linear scale

**Comment by ltalirz** [comment]
I looked a bit into adding a button like this
![image](https://user-images.githubusercontent.com/1053245/93878477-6bceb380-fcda-11ea-9f16-76b5db315a12.png)

Unfortunately, it turned out to be more difficult than expected- simply overriding `self.figure.x_scale = bokeh.models.LogarithmicScale()` does not have any effect on the active plot although the same is done here:
https://github.com/bokeh/bokeh/blob/b56543346bad8cdabe99960e63133619feaafbb7/bokeh/plotting/figure.py#L170-L174

Perhaps one would still need to call `process_axes_and_grid`?
https://github.com/bokeh/bokeh/blob/b56543346bad8cdabe99960e63133619feaafbb7/bokeh/plotting/_plot.py#L93

Simply redrawing the whole plot isn't the solution either, since the figure is created only once in the beginning.
