### ISSUE TITLE
Allow (and encourage) to upload the picture

### ISSUE THREAD

**Issue by danieleongari** [NIST-ISODB/isotherm-digitizer-panel#56]
I was thinking that we can have some advantages by having a figure associated with the entry:

* faster doublechecking of submitted data
* collecting a database image/manualdata that we can use later to train a ML algorithm to parse simpler graphs. 

This is not meant to be published in the nist database but only for our internal use. 

As for the ML protocol, I don't think we will able to reach a 100% automation, but already having an algorithm that in 60% of the cases can extract data and asks you to check them and fill the missing one (skipping the manual clicking on markers) will be quite a significant improve. This would allow an expert user to add up to 100 new entries per hour, with consistent high quality checking.

**Comment by ltalirz** [comment]
This has been incorporated into this digitizer.
