### ISSUE TITLE
how to handle Saturation pressure?

### ISSUE THREAD

**Issue by ltalirz** [NIST-ISODB/isotherm-digitizer-panel#7]
![image](https://user-images.githubusercontent.com/1053245/89795209-694c3c00-db28-11ea-9b10-eb302f3251ab.png)

greyed out in the original digitizer

**Comment by dwsideriusNIST** [comment]
The PHP digitizer required the saturation pressure to be input (switched from gray to black) if "RELATIVE (specify units)" was selected in the dropdown.

The best solution probably depends on the best use of panel, however best to implement:
if (RELATIVE PRESSURE) then
    require SATURATION PRESSURE
else
   continue

Maybe it's done during an error check?

**Comment by ltalirz** [comment]
thanks, Dan! I didn't have more time to work on the digitizer today but I'll continue tomorrow morning before our meeting. See you then!

**Comment by ltalirz** [comment]
fixed in 9ae575ff2e7d24c5c8f0bd000aa67a0818c6c609.

**Comment by ltalirz** [comment]
@dwsideriusNIST by the way, what is the key that should be used for the saturation pressure?
I currently add it conditionally (if specified) using the key `saturationPressure`

**Comment by dwsideriusNIST** [comment]
That is the correct key for the saturation pressure specification, like:
"saturationPressure": 1.0132325

**Comment by ltalirz** [comment]
Thanks!
