### ISSUE TITLE
Re-editing previous data is tricky

### ISSUE THREAD

**Issue by danieleongari** [NIST-ISODB/isotherm-digitizer-panel#79]
It is very nice that on the check page one can select a previous isotherm and go back to the single component-page and edit it. 
However, this got very tricky because some fields were not updated with respect to the current text inside.
This was also true for the attached figure file.

I tested to write something new on e.g., the "adsorbent" field, and when selecting a previous isotherm this was not updated. 

This cause to actually make more errors when trying to correct something.

Browser used: Chrome

**Comment by ltalirz** [comment]
Confirmed:

 * figure image not updated correctly
 * adsorbate name not updated correctly upon reloading (probably results in an exception that then breaks further updating; this should not be the case)
