### ISSUE TITLE
How to handle concentration units?

### ISSUE THREAD

**Issue by ltalirz** [NIST-ISODB/isotherm-digitizer-panel#8]
![image](https://user-images.githubusercontent.com/1053245/89795270-7bc67580-db28-11ea-91a2-18780e3537f2.png)

greyed out in the original digitizer

**Comment by dwsideriusNIST** [comment]
Same handler as for relative pressure. Decide what is best for enforcing an if/then based on the compositionType variable.

**Comment by ltalirz** [comment]
only needed for multi-component, and if the composityion-type attribute is 'concentration'

**Comment by ltalirz** [comment]
fixed in 9ae575ff2e7d24c5c8f0bd000aa67a0818c6c609
