### ISSUE TITLE
tests failing - known issue

### ISSUE THREAD

**Issue by dwsideriusNIST** [NIST-ISODB/isotherm-digitizer-panel#85]
the 'tests' actions in the CI workflow are currently failing due to a network connection error

this appears to be an IPv6 issue on the NIST server that hosts the ISODB API (https://adsorption.nist.gov); some networks are not routing the traffic correctly. I am currently in contact with NIST network engineers to diagnose the problem and find a solution.

**Comment by ltalirz** [comment]
yeah, I also noticed that I couldn't access the web site today

**Comment by ltalirz** [comment]
P.S. if you'd like to be informed about downtimes independently of the NIST IT, there's http://uptimerobot.com/ which offers free checks (I use it for a couple of projects)

**Comment by dwsideriusNIST** [comment]
server is back online. closing issue.
