### ISSUE TITLE
Do we need custom data?

### ISSUE THREAD

**Issue by ltalirz** [NIST-ISODB/isotherm-digitizer-panel#9]
![image](https://user-images.githubusercontent.com/1053245/89795335-8c76eb80-db28-11ea-9cf8-0a76e7712fc2.png)

currently not implemented

**Comment by dwsideriusNIST** [comment]
I would create a field here without any constraints and then just enter the field text as a string value of the "custom" key. It's painless and provides a spot for users to add data that might be useful in the future.

**Comment by ltalirz** [comment]
Only for submission history (does not enter the database).
Students have entered information that helps understanding things like synthesis conditions explaining why isotherms are different.

field string: "custom" - historically contained list of entries, but we can limit it to a single one for simplicity
